on:
  pull_request:
    branches:
      - master

jobs:
  typecheck:
    runs-on: ubuntu-latest
    name: Check for TypeScript Errors
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install packages
        run: npm ci --include=dev
      - name: Run tsc
        run: npm run type-check
